###############################################################
#                   Authelia configuration                    #
###############################################################

host: 0.0.0.0
port: 9091
log_level: debug
jwt_secret: 
default_redirection_url: https://authelia.docker.wwuzerotrust
totp:
  issuer: authelia.com

authentication_backend:
  file:
    path: /etc/authelia/users_database.yml

access_control:
  default_policy: deny
  rules:
    - domain: docker.wwuzerotrust
      policy: one_factor
    - domain: portainer.docker.wwuzerotrust
      policy: one_factor
    - domain: mailhog.docker.wwuzerotrust
      policy: one_factor
    - domain: traefik.docker.wwuzerotrust
      policy: one_factor
    - domain: authelia.docker.wwuzerotrust
      policy: one_factor

session:
  name: authelia_session
  secret: 
  expiration: 3600 # 1 hour
  inactivity: 300 # 5 minutes
  domain: docker.wwuzerotrust # Should match whatever your root protected domain is

regulation:
  max_retries: 3
  find_time: 120
  ban_time: 300

storage:
  local:
    path: /var/lib/authelia/db.sqlite3

notifier:
  filesystem:
    filename: /var/lib/authelia/notification.txt
